# Generated by Django 4.2.1 on 2023-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=250)),
                ('Lname', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
